### ISSUE TITLE
required input is missing: seed

### ISSUE THREAD

**Issue by realyn** [StartHua/Comfyui_CXH_joy_caption#100]
Failed to validate prompt for output 11
CXH_Florence2Run 8:
- Required input is missing: seed
Output will be ignored
Failed to validate prompt for output 2
CXH_Min2_6_prompt_Run 9:
- Required input is missing: seed

CXH_Min2_6_prompt_Run  and CXH_Florence2Run nodes, seed input appeared

**Comment by realyn** [comment]
![WX20241030-183802@2x](https://github.com/user-attachments/assets/ded37693-3d4c-453d-9389-6995a6af9d26)

**Comment by StartHua** [comment]
已修复，comfyui新版问题
