### ISSUE TITLE
I have issues installing the dependency "llama-cpp-python"

### ISSUE THREAD

**Issue by Orenji-Tangerine** [StartHua/Comfyui_CXH_joy_caption#25]
![image](https://github.com/user-attachments/assets/27ee3d95-a7b8-48fe-86e6-b6805babd3d4)

I have problem installing and I have installed C++ Build Tools but still could not get this installed. Previously, I have an older version in my python environmennt but it has problem installing the new version so I uninstalled the old one and now I am trying to install this new version but always stuck at this point.

![image](https://github.com/user-attachments/assets/dc167745-033e-478b-8d72-32eab1d5773a)

**Comment by 0filler** [comment]
same problem. 
Then I have to rollback to save time.

**Comment by Orenji-Tangerine** [comment]
> same problem. 
> Then I have to rollback to save time.

I have asked llama-cpp-python author. I added --verbose error reporting to the pip install and I don't know why it built a successful one after 16 mins. Previously I have waited for like half an hour without anything moving...
