### ISSUE TITLE
OSError: Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory E:/comfyui/models/clip\siglip-so400m-patch14-384.

### ISSUE THREAD

**Issue by qw381523977** [StartHua/Comfyui_CXH_joy_caption#52]
![image](https://github.com/user-attachments/assets/741d1730-23cb-4115-be7a-78f4665e3534)

**Comment by EfrenJ008** [comment]
I am also facing this problem. Could you please advise on how to solve it

**Comment by qw381523977** [comment]
> I am also facing this problem. Could you please advise on how to solve it

Finally I found that in other places it automatically creates a directory into which you can copy the models or you can consider reinstalling comfyui.
