### ISSUE TITLE
Joy_caption User specified an unsupported autocast device_type 'cuda:0'

### ISSUE THREAD

**Issue by HqInqING** [StartHua/Comfyui_CXH_joy_caption#57]
Joy_caption
User specified an unsupported autocast device_type 'cuda:0'

# ComfyUI Error Report
## Error Details
- **Node Type:** Joy_caption
- **Exception Type:** RuntimeError
- **Exception Message:** User specified an unsupported autocast device_type 'cuda:0'

**Comment by GoodGoodstudy0daydayup** [comment]
how did you fixed it?

**Comment by yankyankyank** [comment]
same problem, any solutions by chance?
