### ISSUE TITLE
Joy_caption_alpha_prompt这个节点从name开始所有选项错了一位。

### ISSUE THREAD

**Issue by DragonQuix** [StartHua/Comfyui_CXH_joy_caption#83]
比如name里面只要填了东西，那么下一个选项“如果图像中有人物/角色，你必须用name来指代他们。”就为true，否则为false；而“如果图像中有人物/角色，你必须用name来指代他们。”这个项目的开关，实际上控制的是下面一行“不要包含无法改变的人物/角色信息如:种族、性别等，但要包含可以改变的属性如:发型。”的开和关，如此类推。

**Comment by StartHua** [comment]
以修复谢谢提醒
